data:
    name: 'distillation'
    image_dirs: ['self_driving/images/images1', 'self_driving/images/images2']
    shuffle: false
    preprocessing:
        resize: [480, 640]
        grayscale: false
model:
    name: 'netvlad_original'
    image_channels: 3
weights: 'vd16_pitts30k_conv5_3_vlad_preL2_intra_white/vd16_pitts30k_conv5_3_vlad_preL2_intra_white'
